/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "Source Team Attack Control",
	author = "Rothgar, FlyingMongoose",
	description = "This is a TK and TA control plugin meant for the Source Engine",
	version = "0.1",
	url = "https://github.com/dawgclan/stac"
}

public OnPluginStart()
{
	// Add your own code here...
}
